name: Post-Merge Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-tag-and-release:
    runs-on: self-hosted
    if: |
      github.event.pull_request.merged == true &&
      !contains(github.event.pull_request.labels.*.name, 'do-not-release')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GHA_TOKEN }}
          
      - name: Configure git
        run: |
            git config user.name "urafiz"
            git config user.email "kratser88@gmail.com"
    
      - name: Extract version from PR title or package.json
        id: extract-version
        run: |
          # Try to extract version from PR title format: "[Automation] Version bump to X.Y.Z"
          VERSION=$(echo "${{ github.event.pull_request.title }}" | sed -n 's/.*Version bump to \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
          if [ -z "$VERSION" ]; then
            echo "Could not extract version from PR title, falling back to package.json"
            VERSION=$(node -p "require('./package.json').version")
          fi
          if [ -z "$VERSION" ]; then
            echo "Failed to extract version from both PR title and package.json"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
      
      - name: Create and push tag
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
          echo "Created and pushed tag v${{ env.VERSION }}"
      
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          RELEASE_URL=$(gh release create "v${{ env.VERSION }}" \
            --title "Release v${{ env.VERSION }}" \
            --notes "Release automatically created from PR #$PR_NUMBER: $PR_TITLE" \
            --generate-notes)
          
          echo "Created release: $RELEASE_URL"
      