name: PR Version Bump

on:
  pull_request:
    types: [labeled]

jobs:
  update-version-in-pr:
    runs-on: self-hosted
    # Only run this on PRs with semver labels
    # Only run this on PRs with semver labels (skip do-not-release)
    if: |
      github.event.label.name == 'major' || 
      github.event.label.name == 'minor' || 
      github.event.label.name == 'patch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{secrets.GHA_TOKEN}}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure git
        run: |
            git config user.name "urafiz"
            git config user.email "kratser88@gmail.com"
    
      - name: Increment version in package.json
        run: |
          # Extract the semver label
          LABEL="${{ github.event.label.name }}"
          echo "Using label: $LABEL"
          
          # Get current version before bump
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Bump version according to label
          NEW_VERSION=$(npm version $LABEL --no-git-tag-version | sed 's/^v//')
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
          # Stage the changes
          git add package.json

      - name: Commit and push version change
        run: |
          # Create commit with version bump
          git commit -m "[Automation] Bump version to ${{ env.NEW_VERSION }} based on '${{ github.event.label.name }}' label"
          
          # Push to the same PR branch
          git push origin HEAD:${{ github.head_ref }}

      - name: Install GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y curl
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y gh
          else
            echo "GitHub CLI (gh) is already installed."
          fi

      - name: Add PR comment
        env:
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -b "✅ Version bumped to **v${{ env.NEW_VERSION }}** in this PR based on the '${{ github.event.label.name }}' label.

          The version change has been committed to this PR. Upon merge, a release tag will be automatically created."

