name: CI

on:
    pull_request:
      types: [closed]
      branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true &&
      !contains(github.event.pull_request.labels.*.name, 'do-not-release')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GHA_TOKEN}}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure git
        run: |
            git config user.name "user"
            git config user.email "user@gmail.com"
    
      - name: Extract version label
        if: github.event_name == 'pull_request'
        id: extract-label
        run: echo "LABEL=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[0].name')" >> $GITHUB_ENV

      - name: Set default version label
        if: github.event_name == 'push'
        run: echo "LABEL=patch" >> $GITHUB_ENV

      - name: Bump version number
        run: |
          yarn version --${{ env.LABEL }} --message "[no ci]: Bump ${{ env.LABEL }} version"
          echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      
      - name: Push changes (tags only)
        run: |
          git push --tags origin main
      
      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: |
          gh release create ${{ env.TAG }} --generate-notes
      
      - name: Publish components to Github package repository
        run: |
          npm config set @org:registry https://npm.pkg.github.com
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHA_TOKEN}}

